### ISSUE TITLE
Sort Plugins button too hidden with new UI

### ISSUE THREAD

**Issue by Nazenn** [loot/skyrim#105]
Since the new UI was introduced a few versions ago, there has been a huge influx of support requests on various modding communities in regards to issues with load order that are found to have originated at the start with confusion about the new LOOT.

Because LOOT now immediately displays a load order compared to the last version, people think just running it is enough and don't notice the Sort Plugins button. As a result a lot of people think they have run LOOT on their load order but don't realize it has more steps and as such aren't properly applying LOOTs changes or receiving LOOT's warnings.

On average I see approximately two to three reports per day of help issues where LOOT has not properly been used due to people not being able to easily find the sort button.

I propose that this be changed into text instead of a symbol as the symbol is too ambiguous and not easily recognizable, as well as a warning, perhaps that can be optionally turned off, that if people try and close the program without actually hitting Sort Plugins and Apply, it delivers a warning that they have not properly applied the changes to their load order and asks them to confirm that they do want to leave before sorting their load order.

I understand you can't account for everyone or everything, but right now it really is a major thing with people being adamant that they have run LOOT only to realize the real option is hidden away and they hadn't been running it all along.

**Comment by WrinklyNinja** [comment]
Please re-file this on the [correct issue tracker](https://github.com/loot/loot/issues).

**Comment by Nazenn** [comment]
Sorry about that, this was the link I was provided by one of your team, so I didn't really think about double checking it

**Comment by Freso** [comment]
> this was the link I was provided by one of your team

Yes, for filing issues with Skyrim's masterlist. :) I also linked you to the issue tracker @WrinklyNinja linked you to for reporting this bug you've not finally gotten around  to reporting. ;)

For anyone wondering, this issue is now being tracked at https://github.com/loot/loot/issues/528
