### ISSUE TITLE
ELE_Legendary_Lite.esp should sort after Relighting Skyrim

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#108]
This report [ticked in on IRC](https://botbot.me/freenode/loot/msg/62347004/)

> ELE_legendary_lite.esp is always getting sorted above the plugins for Relighting Skyrim although the author for ELE Lite explicitly says to place anyy ELE plugin under any one of the Relighting Skyrim plugins.
> I'd just like to leave a message here and hopefully you will remedy this mistake. thank you. :)
> ah, it's actually ELE_Legendary_Lite.esp

**Comment by Thallassa** [comment]
Checked in TES5edit. Was surprised that I can confirm, ELE must be after RLS. 

I thought RLS only did lightbulbs but apparently it does lighting changes as well.
