### ISSUE TITLE
LOOT stopped sorting mods

### ISSUE THREAD

**Issue by javishpr** [loot/skyrim#109]
I've noticed for the last couple of weeks I been playing Skyrim and trying some mods here and there that LOOT is not sorting these mods (or the existing ones I have). I use Mod Organizer and depending on my play style for that particular play-through is the mods I will enable (or add new ones). Once I enable or add new mods all plugins are at the bottom of my load order. When I run LOOT and it finishes the mods are still at the bottom of my load order. With the exception of "Alternate Start - Live Another Life" mod that is always place a the end. 
Even if I move any of the already there plugins, LOOT won't put them back to their original place. They will remain at the bottom of the plugins list with all the other mods I enable or added.
I also tried reinstalling LOOT and got the same results as described above. Even using the sorting button that Mod Organizer has (which I think uses LOOT masterlist) the plugins remain the same.

**Comment by Ortham** [comment]
LOOT won't move plugins it sees no reason to move. If you know they're in the wrong place where they are, then metadata needs to be added for them so that they get put in correct positions.

**Comment by javishpr** [comment]
Well I'm talking about plugins that LOOT put in those positions back when I installed those mods (a long while ago) and now LOOT is just leaving them at the bottom. That's why I move them to see if they were put back to their original positions and it didn't happen. Don't know, maybe I'm being silly and LOOT is working as intended. Just thought it was strange that mods I've used for a very long time and know that LOOT moved them there weren't being moved. Thanks for the reply, appreciate it!

**Comment by Ortham** [comment]
> Just thought it was strange that mods I've used for a very long time and know that LOOT moved them there weren't being moved.

Older versions of LOOT would move all plugins, so that could be why you saw LOOT moving them before.

Closing this, as there doesn't seem to be an issue.
