### ISSUE TITLE
wrong load order with Underground Bathhouse Merge

### ISSUE THREAD

**Issue by ulli5** [loot/skyrim#110]
http://www.nexusmods.com/skyrim/mods/32235/?
"Load order matters on this file. It must come after all BBLS files and before all UB files especially the cell files or you might have a navmesh issue in the BBLS or missing doors in the Underground Bathhouse."
Actually LOOT loads this Mod after the UB files and some UB cells are missing in game.

[Metadata.txt](https://github.com/loot/skyrim/files/212341/Metadata.txt)

**Comment by Freso** [comment]
What about `ub_cell_teleportroom.esp` and `ub_disable_teleportroom.esp`?
