### ISSUE TITLE
Lakeside Manor - ITMs and UDRs

### ISSUE THREAD

**Issue by Thallassa** [loot/skyrim#112]
Lakeside Manor - Lakeside Manor.esp - 11 deleted records, 7 ITMs

http://www.nexusmods.com/skyrim/mods/20266/?

(I didn't think it was worth posting here since it has so few downloads, but a. Freso annoyed me to do it and b. I just posted a review about the mod that made note of these, so it'd be very hypocritical to not list them here as well). 

I kind of suspect there is more than one mod with an esp named Lakeside Manor.esp, I don't know how your team handles that.

**Comment by Freso** [comment]
> I kind of suspect there is more than one mod with an esp named Lakeside Manor.esp, I don't know how your team handles that.

ITMs and deleted records are coupled with a checksum of the file in question, so unless there's another mod with the same filename with identical contents, it shouldn't be an issue.

**Comment by pStyl3** [comment]
/skyrim/mods/20266 provides two plugins / variants of "Lakeside Manor.esp", CRCs are:
D26D0D22
B8F91EA1

Both contain said 7 ITMs and 11 deleted references. I used the latest version of xEdit to confirm Thallassa's numbers ("FO4Edit 3.1.3 - 7f5c252-2737-3-1-3.7z").

**Comment by Freso** [comment]
Seems like those two CRCs were already added in commits ada8e9f27e1c084584e46eee059dde90f8c597e3 (`0xb8f91ea1`, added to wrong(?) .esp at the time, but my investigation didn't find where/when it was moved to the proper one, though it sits with `Lakeside Manor.esp` in the current version of the masterlist) and 5438897219f85d7a76b8aa943dc81f2a324852c4 (`itm` for `0xd26d0d22`) as well as all the way back from the official conversion from the BOSS masterlist: 230f77179ca56bd4a93b33189019197e300bfa4c

@Thallassa or @pStyl3, can you confirm that the unaltered .esp's downloaded from http://www.nexusmods.com/skyrim/mods/20266/ do not show the dirty plugin warnings/messages?

**Comment by pStyl3** [comment]
LOOT shows the dirty plugin message for both plugins .. now I'm wondering why I didn't saw that before ... could be that I just looked at the CRC within LOOT without looking at "everything else" in the plugin card.

There is still the question why Thallassa didn't notice the warning message, but from my point of view everything seems to be good already.

**Comment by Thallassa** [comment]
It's entirely possible that I didn't run LOOT on it and just assumed the
mod wasn't there because it had, like, 13 downloads XD

**Comment by Freso** [comment]
Closing for now then. :)
