### ISSUE TITLE
Plugin error. Unlimited Bookshelves.

### ISSUE THREAD

**Issue by yrc64cjgfccdx** [loot/skyrim#113]
Error:
UnlimitedBookshelves.esp  6B98D61C
This plugin requires "Unofficial Skyrim Patch.esp" to be installed, but it is missing.

Aleady have an Unofficial Skyrim Legendary Edition Patch installed, will it crash or wont work if I install Unofficial Skyrim Patch?

**Comment by Ortham** [comment]
IIRC, plugins which require the non-Legendary Edition patch won't necessarily work with the LE patch. You'll have to find out for yourself or ask the author though.
