### ISSUE TITLE
CACO should sort after CCOR

### ISSUE THREAD

**Issue by Thallassa** [loot/skyrim#114]
I sorted the other day with the current version of the masterlist and noticed this was not sorted correctly.

Complete Alchemy & Cooking Overhaul.esp must sort after Complete Crafting Overhaul_Remade.esp

(it must also sort after disparity.esp)

This is on the mod description page for CACO and I've confirmed it in TES5edit.

**Comment by Freso** [comment]
Do you have a link handy to the mod page(s)?

**Comment by Thallassa** [comment]
Derp! http://www.nexusmods.com/skyrim/mods/69306/ and http://www.nexusmods.com/skyrim/mods/49791/?
And disparity: http://www.nexusmods.com/skyrim/mods/63354/?
