### ISSUE TITLE
Loot Crash ntdll.dll

### ISSUE THREAD

**Issue by Altarya** [loot/skyrim#116]
Hello everyone, devs and users alike,

I am Altarya, a Skyrim player, with just about 255 mods and 70 not activated, yes it is a lot, and thus i require a load optimization tool, and while NMM's built-in tool is practical and all it is far from the best, so i started using LOOT about an year ago, and it was working fine until it decided to crash and burn and not even start anymore, i literally click to open it and it crashes with the following message:

Problem signature:  
Problem Event Name: APPCRASH  
Application Name:   LOOT.exe  
Application Version:    0.9.1.0  
Application Timestamp:  576b84b3  
Fault Module Name:  ntdll.dll  
Fault Module Version:   6.1.7601.23418  
Fault Module Timestamp: 5708a73e  
Exception Code: c0000005  
Exception Offset:   0004e6df  
OS Version: 6.1.7601.2.1.0.256.1  
Locale ID:  1046  
Additional Information 1:   a877  
Additional Information 2:   a87751724e225ffcdd7aaed29770c8da  
Additional Information 3:   6ac2  
Additional Information 4:   6ac2897ccd75043f0668e4426e4bf347

So what i've already done:
1 - Re-installed the ntdll.dll via a microsoft hotfix
2 - Updated display drivers
3 - Re-installed LOOT several times
4 - restored the System to a point where LOOT was working
5 - tried to pin-point the error with Visual Studio, but VS wouldn't even load LOOT, it just complained about the ntdll.dll as well(not that VS isn't working, it is, but it wouldn't start loot up thanks to the dll).
6 - started LOOT with administrative elevation, 
7 - copied and pasted the ntdll.dll file to LOOT's installation folder
8 - download a clean ntdll.dll file and placed it in LOOT's installation folder
9 - used process explorer to find out what was using ntdll.dll and the following:
![image](https://cloud.githubusercontent.com/assets/20309104/16602948/98ab1b96-42ee-11e6-8bce-70e641e0f592.png)

I have no idea what to do anymore.

Best regards,
“Altarya„

**Comment by Altarya** [comment]
Oh yes, i also checked for viruses with ESET NOD32 9, on my WHOLE computer and BOTH the 32-bit and 64-bit ntdll.dll files, with nothing found

**Comment by Altarya** [comment]
Hardware is the following:

GPU, BIOS, etc...:
![image](https://cloud.githubusercontent.com/assets/20309104/16603140/3f4b4790-42f0-11e6-9e77-0688de688a68.png)

CPU, system, etc...:
![image](https://cloud.githubusercontent.com/assets/20309104/16603151/529f3824-42f0-11e6-9c62-532f8eb30984.png)

Display Driver:
![image](https://cloud.githubusercontent.com/assets/20309104/16603164/6ac3d52c-42f0-11e6-9868-f9e349129635.png)

**Comment by Ortham** [comment]
Do [the latest snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0), [v0.9.0](https://github.com/loot/loot/releases/tag/0.9.0) or [v0.8.1](https://github.com/loot/loot/releases/tag/v0.8.1) work?

**Comment by Altarya** [comment]
Greetings, and thanks for the answer,

Please excuse me for taking so long to reply back, i had a few issues with my internet for last month or so.

Nope, none of them work, they all crashed with the same exact same error...

“Altarya DeFlammes„

**Comment by Freso** [comment]
I don't see anywhere in what you have tried that you tried to remove the `%LOCALAPPDATA%\LOOT` folder. Perhaps try to do a clean install of LOOT (no ntdll.dll or other files not included with LOOT normally) but also without the `%LOCALAPPDATA%\LOOT` folder.

If it still doesn't work even after this, please follow the steps at https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html and upload the debug logs produced.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
