### ISSUE TITLE
Failed to update masterlist

### ISSUE THREAD

**Issue by QuinRiva** [loot/skyrim#124]
I'm getting an error with "Failed to update masterlist".  Given the error description, I suspect that it is because my "TEMP" folder is not on my system drive, or my "Users" drive:

Error code: -1; Failed to update the masterlist. Details: boost::filesystem::rename: Access is denied: "H:\Users\quinriva\AppData\Local\LOOT\Skyrim", "E:\Temp\cda4-eaf2-b463-f0b5"

**Comment by QuinRiva** [comment]
Seems to be confirmed.  Changing TMP from E:\Temp to H:\Temp seems to fix the issue.

Can the code be updated from boost::filesystem::rename to move?  I guessing that would resolve the issue?

**Comment by Ortham** [comment]
Could you please re-file this on [the correct issue tracker](https://github.com/loot/loot/issues)?
