### ISSUE TITLE
Loot never updates my load order

### ISSUE THREAD

**Issue by iCeeskyyy** [loot/skyrim#125]
So Loot won't change my load order at all even when it is wrong it doesn't detect it or change it and i don't know what to do to try and get it to work

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
