### ISSUE TITLE
LOOT reporting SKSE outdated

### ISSUE THREAD

**Issue by SillySnowFox** [loot/skyrim#127]
The ingame menu reports version 1.7.3 installed, the skse website reports the current version as 1.7.3 LOOT claims my skse is outdated.

**Comment by Ortham** [comment]
I can't replicate this - what does your `skse_loader.exe` have for its `File version` in its Properties (on the Details tab)?

**Comment by Ortham** [comment]
Also, check that your Skyrim masterlist branch is set to `v0.8` (and that you're using LOOT v0.8+).

**Comment by SillySnowFox** [comment]
0.1.7.2 odd, the in game display shows 1.7.3

Masterbranch is set to 0.8

**Comment by SillySnowFox** [comment]
If it helps any I have skse installed through steam

**Comment by Ortham** [comment]
> If it helps any I have skse installed through steam

So do I, try verifying its game cache integrity.

**Comment by SillySnowFox** [comment]
There it goes, seems steam didn't update a couple files the last time it did it's thing. I'll try that if it does it again, thanks.
