### ISSUE TITLE
error to initiate loot (problemas para iniciar Loot)

### ISSUE THREAD

**Issue by Aluizx6** [loot/skyrim#131]
![sem titulo](https://cloud.githubusercontent.com/assets/24538117/21128253/90ec981a-c0e0-11e6-8f7d-d3d684529eb2.png)

segue anexo
![sem titulo](https://cloud.githubusercontent.com/assets/24538117/21128292/d458977a-c0e0-11e6-9408-23724dacff83.png)

**Comment by Ortham** [comment]
Closing this as a duplicate of loot/loot#730.
