### ISSUE TITLE
Blocking load of ressource + libloadorder fail

### ISSUE THREAD

**Issue by Tonher31** [loot/skyrim#133]
Whenever I try to use Loot for Skyrim (not Special Edition), it doesn't work. I've attached the debug files for you to understand whats going on

[CEFDebugLog.txt](https://github.com/loot/skyrim/files/791537/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/791538/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Can you enable debug logging and post the LOOTDebugLog.txt it generates?

**Comment by Tonher31** [comment]
I enabled it
Aaaaaaaaand... I LOOT worked. It's strange because i didn't do anything

So I guess the issue can be closed

**Comment by Ortham** [comment]
OK. If it happens again, just reopen the issue.
