### ISSUE TITLE
Skyrim masterlist Msg string content syntax not working

### ISSUE THREAD

**Issue by rockerfahis** [loot/skyrim#137]
![screenshot 8](https://user-images.githubusercontent.com/29510611/27256481-a77d22f6-537b-11e7-86f0-0b6fb7dbef13.png)
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1082762/LOOTDebugLog.txt)

I dont think this is working correctly cause i cant add user bash tags to this mod

**Comment by rockerfahis** [comment]
it happened with several other mods too

**Comment by Freso** [comment]
Halløj :)

What are you trying to do? Adding bash tags directly to the masterlist file, or adding bash tags via user metadata editor? Why do you think it isn't working? (I can't tell what you're trying to say with the attached screenshot, sorry.)

**Comment by Ortham** [comment]
Well, it's got nothing to do with adding Bash Tags, but I don't know why the Content fields are blank in that table for you, they're not for me. What version of LOOT are you using?

**Comment by Ortham** [comment]
Oh, wait, if I re-clone the masterlist repo I get empty fields too... Ah, it's because the message structures aren't flattened when sent by the update callback, I'll file a bug for that.

**Comment by Freso** [comment]
Closing this as the issue has been copied/moved to the proper repository. Follow https://github.com/loot/loot/issues/792 for updates.

**Comment by rockerfahis** [comment]
i cant add bash tags via the user metadata editor

**Comment by Ortham** [comment]
> i cant add bash tags via the user metadata editor

What happens when you try? The screenshot you provided doesn't seem to show anything relevant.
