### ISSUE TITLE
Skyrim Radioactive NULL REFERENCE Records

### ISSUE THREAD

**Issue by Sulhir** [loot/skyrim#139]
http://www.nexusmods.com/skyrim/mods/59871/? Skyrim Radioactive
SkyR - Riverwood Interiors.esp  F4A6BF2C version 1.4
Contains 17 temporary NULL REFERENCE files in Faendal's House.

Fraid I don't know enough for making a fancy shmancy pull request :(

**Comment by Ortham** [comment]
Closing this as #182 fixes it.
