### ISSUE TITLE
ELFX and global_priority

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#144]
Due to the userlist in https://github.com/loot/skyrim/issues/142 I had (and is having) a long discussion on the [/r/skyrimmods](https://www.reddit.com/r/skyrimmods/) IRC channel with @LordOfLA and @Neffistopheles about ELFX, its placement and `global_priority`s.

In commit 28699f28b7e7e77d948a2a9e7d1732400d6f1632 @Kaenguru-Knobel-Kette added a `global_priority` to `ELFXEnhancer.esp`, but I was arguing in #skyrimmods that it would be better to give the plugin a heavy `priority` instead, to load it only after any plugins it shares records with, rather than after (almost) all other plugins. One of the arguments against this on IRC was that `ELFXEnhancer.esp` touches top cell records but not their children's (@Neffistopheles):
> ELXEnhancer.esp must be last, because it touches top level cell records, but not cell contents, so every mod that does anything with a cell overwrites it.

I asked @LordOfLA to try and do some testing based on this, but since a lot of ELFX related plugins are apparently now in `global_priority: 75`, it might be difficult to test doing only userlist edits. @WrinklyNinja, do you know whether LOOT will consider two plugins conflicting if one plugin only touches a top-level record and the other only a child record of this top-level record?

If we decide we want to retain `global_priority: 75` for all of these ELFX plugins, this should be noted on the [Global Priorities](https://loot.github.io/docs/contributing/Global-Priorities.html) reference page too.

**Comment by Ortham** [comment]
> @WrinklyNinja, do you know whether LOOT will consider two plugins conflicting if one plugin only touches a top-level record and the other only a child record of this top-level record?

Nope, conflicts are only between records with the same source plugin and object ID.

**Comment by MacSplody** [comment]
I guess this can be closed now?
 
 - name: ELFXEnhancer.esp
    group: Lighting
