### ISSUE TITLE
Permutation problem

### ISSUE THREAD

**Issue by deathlyy** [loot/skyrim#146]
Alternate Start -New Beginnings. Esp is in the back of Alternate Start -live Anotther Life.
It's at the back of the line.

**Comment by Freso** [comment]
I'm not entirely sure what you're saying or asking here. Are you saying that the file `Alternate Start -New Beginnings. Esp` is being loaded earlier/before or later/after the file `Alternate Start -live Anotther Life`(`.esp`?)? And that it shouldn't be?

Please give full and exact plugin filenames, and give concrete examples of what you're trying to do, what is happening, and what you expected to happen instead.

**Comment by deathlyy** [comment]
As you understand " Alternate Start - Live Another Life " The extension of mod" New Beginnings - Live Another Life Extension" Lined up behind him, now is " Did not identify & quot; (in the back)

**Comment by Freso** [comment]
I don't understand, no. Sorry. :( @WrinklyNinja? Or @Kaenguru-Knobel-Kette maybe?

**Comment by Ortham** [comment]
Nope, I can't make anything of it either.

@deathlyy: I'm guessing English isn't your native language, try writing in your native language and maybe we can translate.

**Comment by deathlyy** [comment]
emmmmm How do I interpret it in my native language。。。。。。
"New undy-live Another Life Extension" 这个MOD 排列在"Alternate start-live Another Life"的后面

现在他是在列表的最后面 是无法识别自动排在最后面的

**Comment by deathlyy** [comment]
emmmmm How do I interpret it in my native language。。。。。。
"New undy-live Another Life Extension" 这个MOD 排列在"Alternate start-live Another Life"的后面

现在他是在这个MOD其他MOD的后面

**Comment by deathlyy** [comment]
emmmmm How do I interpret it in my native language。。。。。。
"New undy-live Another Life Extension" 这个MOD 排列在"Alternate start-live Another Life"的后面

现在"New undy-live Another Life Extension" 在"Alternate start-live Another Life"隔着的2个MOD的后面

**Comment by deathlyy** [comment]
emmmmm How do I interpret it in my native language。。。。。。
"New undy-live Another Life Extension" 这个MOD 排列在"Alternate start-live Another Life"的后面
（中间不能有任何的MOD）

现在"New undy-live Another Life Extension" 在"Alternate start-live Another Life"隔着的2个MOD的后面

**Comment by deathlyy** [comment]
这是转载的人要求的，也许是他们的经验吧

**Comment by Ortham** [comment]
That didn't really help... I assume you're referring to [this mod](https://www.nexusmods.com/skyrim/mods/70959/) in relation to Live Another Life, but it's already got the latter as a master, so it has to be loading in the correct order.
