### ISSUE TITLE
Relationship Dialogue Overhaul load order changes

### ISSUE THREAD

**Issue by Thallassa** [loot/skyrim#150]
RDO: https://www.nexusmods.com/skyrim/mods/74568/ states in its description that it should be loaded after Guard Dialogue Overhaul. I believe that this is the correct recommendation. LOOT currently sorts GDO after. 

GDO: https://www.nexusmods.com/skyrim/mods/23390/

In addition RDO should load after Alternate Start - Live Another Life https://www.nexusmods.com/skyrim/mods/9557/? as per the mod description. (I haven't checked if this is the wisest thing).

**Comment by MacSplody** [comment]
#206
