### ISSUE TITLE
Repeated messages

### ISSUE THREAD

**Issue by Ortham** [loot/skyrim#152]
These should be aliased:

`Use non-Dawnguard version.`
`Plugin has some corruption.` - there's probably an existing aliased message that could be used instead.
`Use Dawnguard version.` - also `Dawnguard version required.`
`Use Hearthfires version.`
`Do not clean the file further with TES5Edit.`
`Incompatible with: Mighty Magic`

Also it may be worth aliasing `Incompatible with: X` more generically.

**Comment by pStyl3** [comment]
Done as of commit https://github.com/loot/skyrim/commit/9f55a1b5b0375bb6898e3cc91db4e42aa0ea415a.
