### ISSUE TITLE
Replace some incompatible with messages

### ISSUE THREAD

**Issue by Ortham** [loot/skyrim#153]
These use regex for a small number of variations, so would be better as `inc` objects:

`Incompatible with: NA_Trueflame_Eng or Rus esp`
`Incompatible with: WeaponsOf3E*.esp`

**Comment by kuroko137** [comment]
#152, #153
Okay, got it. For now I'll remove redundant contents .
Thank you for the merge request!

**Comment by pStyl3** [comment]
First batch done as of https://github.com/loot/skyrim/commit/d0ca03afc789bfd9d86936ba3749ab21a57ad768.
There are still more `Incompatible with:` messages to rework, but that's a task for another day.

**Comment by pStyl3** [comment]
With the second PR merged, this issue can be closed.
