### ISSUE TITLE
More salt mod, intended ITM

### ISSUE THREAD

**Issue by heavyoak** [loot/skyrim#156]
https://www.nexusmods.com/skyrim/mods/22273/?

> "Dirty entry: 1 ITM, ignore it. It is needed, no guarantee it works without."

 
>MoreSalt.esp 
> 492E06A5
> Relev
> TES5Edit found 1 ITM record. A cleaning guide is available here.

note sure if this is the right spot to submit this, but loot shouldn't be telling me to clean something that will break when clean per the makers own words.

**Comment by Ortham** [comment]
The author's explanation seems reasonable, I'll change it to a do not clean message.
