### ISSUE TITLE
No masterlist

### ISSUE THREAD

**Issue by Kahldris15** [loot/skyrim#165]
Hello I have read through topics and tried everything with nothing working. Basically Loot has no masterlist, I have tried disabling the firewall, I have tried given all the permissions and running as administrator and more. All to no avail, this is what pops up when I try to update the masterlist for skyrim.

Basically "oops something went wrong check your lootdebug", in that file it says this:

[warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[18:51:26.680191] [warning]: No masterlist present at "C:\Users\Kahldris\AppData\Local\LOOT\Skyrim\masterlist.yaml"
[18:51:29.569756] [error]: Git operation failed. Details: -1; failed to send request: A connection with the server could not be established

: libgit2 error

I have windows 10 and the most current version of loot 0.12.1

Really weird please help!!!

**Comment by Ortham** [comment]
Strange, since you can clearly access GitHub through your browser. Do you have an antivirus or firewall or something that could be blocking LOOT?

**Comment by Kahldris15** [comment]
Well again I tried turning my firewall off (loot isn't showing up in the list of programs in the firewall which I thought weird so I just tried turning it off). I exited out of Malwarebytes program. 

I just went through my programs and I don't think I have anything else that would block loot. 

The other debug file the CEFD says this:  (in case it will help) [0201/130658.182:ERROR:main_delegate.cc(713)] Could not load cef_extensions.pak

I feel like Loot should be working fine but yet I have no masterlist and uh I cant sort my mods!

I have the update masterlist before sorting in the setting menu on and turned on debug logging as well just to see if that did anything.......

**Comment by Kahldris15** [comment]
I am using NMM for my mods and uh ya I am at a complete loss. I used the installer to install loot.

**Comment by Kahldris15** [comment]
I installed it on my main drive in its own folder (in case program files was causing an issue).

**Comment by Kahldris15** [comment]
I have also tried re installing several times....

**Comment by Ortham** [comment]
You don't use a proxy that your web browser is aware of but LOOT isn't, do you?

**Comment by Kahldris15** [comment]
Not currently using one and I don't currently have anything installed.

**Comment by Kahldris15** [comment]
Any other ideas? This is getting frustrating to me... so much for revisiting skyrim!

**Comment by Kahldris15** [comment]
Loot still says this in the main window.

Masterlist Revision	N/A: No masterlist present
Masterlist Date	N/A: No masterlist present

**Comment by Kahldris15** [comment]
Can I manually install the masterlist? If so how do I do it? I would rather get loot working properly but if it wont maybe I can at least install the masterlist manually....

**Comment by Ortham** [comment]
You can install it manually by downloading this repository's masterlist.yaml and putting it at `%LOCALAPPDATA%\LOOT\Skyrim\masterlist.yaml`.

**Comment by Kahldris15** [comment]
Okay so I go here https://github.com/loot/skyrim

But jump to file and grab the masterlist.yaml read me file? I feel dumb here but not seeing a download button.

**Comment by Ortham** [comment]
https://raw.githubusercontent.com/loot/skyrim/v0.10/masterlist.yaml

You need to click on the masterlist.yaml and then click the "Raw" button.

**Comment by Kahldris15** [comment]
okay gotcha but then what? lol no way to dl the raw file and uh I cant just copy and paste....

**Comment by Ortham** [comment]
Right click the page and click "Save as..." or whatever your browser's equivalent is. You can also right-click the link and do "Save link as..." or similar too.

**Comment by Kahldris15** [comment]
An error occurred while parsing the metadata list(s): Cannot open C:\Users\Kahldris\AppData\Local\LOOT\Skyrim\masterlist.yaml.
Try updating your masterlist to resolve the error. If the error is with your user metadata, this probably happened because an update to LOOT changed its metadata syntax support. Your user metadata will have to be updated manually.
To do so, use the 'Open Debug Log Location' in LOOT's main menu to open its data folder, then open your 'userlist.yaml' file in the relevant game folder. You can then edit the metadata it contains with reference to the documentation, which is accessible through LOOT's main menu.
You can also seek support on LOOT's forum thread, which is linked to on LOOT's website.

**Comment by Kahldris15** [comment]
Masterlist Revision	Unknown: Git repository missing
Masterlist Date	Unknown: Git repository missing

**Comment by Ortham** [comment]
> An error occurred while parsing the metadata list(s): Cannot open C:\Users\Kahldris\AppData\Local\LOOT\Skyrim\masterlist.yaml.

I'm not sure why you're getting that error, I can't replicate it.

> Masterlist Revision Unknown: Git repository missing
> Masterlist Date Unknown: Git repository missing

That's expected since you downloaded the masterlist manually.

**Comment by Kahldris15** [comment]
I'm just resetting my computer ive had this one for about a year anyway I don't like it when things don't work as they should and I cant figure it out lol. Ill let u know if loot works after that!

**Comment by Kahldris15** [comment]
Alright resetting the computer fixed the problem. I still have no idea what the heck was going on and I wish I could have figured it out so I would have known but whatever. Thanks for trying to help.

**Comment by Ortham** [comment]
OK, closing this then.
