### ISSUE TITLE
Skyrim LOOT sorting plugins issue. 

### ISSUE THREAD

**Issue by igotsometrouble** [loot/skyrim#166]
I'm currently running the most up to date LOOT, I just reinstalled it to, to make sure. 
when I attempt to 'sort plugins' for Skyrim I get a error (Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.) this stops it from sorting in the end when I go check my debug all I get is. 
 CEFdebuglog: [0207/113050.202:ERROR:main_delegate.cc(713)] Could not load cef_extensions.pak

as for LOOTdebuglog it is empty. so I'm unable to find a solution as a result I'm unable to sort my load order or check for dirty plugins.

**Comment by Ortham** [comment]
The LOOT debug log shouldn't be empty, can you enable debug logging and try again? See [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) for details.

**Comment by igotsometrouble** [comment]
[19:57:48.979903] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic is the warning at the top of the debug. the rest I assume is not so important.

**Comment by Ortham** [comment]
The rest is far more important, considering that warning is intentional and happens for everyone...

Don't copy/paste the file content, just upload the file.

**Comment by igotsometrouble** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1706346/LOOTDebugLog.txt)

I have allowed it through the firewall to its still not working, there is the debug file.

**Comment by igotsometrouble** [comment]
my file has changed again after trying to sought my plugins again. I have 102 mods and they are all installed through NMM following correct install procedures. 
 
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1706412/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
```
[20:26:26.483755] [error]: Cannot read plugin file "StojaMakeupPack.esp". Details: D:\Prograam File (x86)\Steam\steamapps\common\Skyrim\Data\StojaMakeupPack.esp : Libespm error code: 5`
...
[20:26:26.483788] [trace]: Caught exception while trying to add StojaMakeupPack.esp to the cache: Cannot read "StojaMakeupPack.esp". Details: D:\Prograam File (x86)\Steam\steamapps\common\Skyrim\Data\StojaMakeupPack.esp : Libespm error code: 5
```

It looks like esplugin (not libespm, the error message is out of date) thinks there's something wrong with the `StojaMakeupPack.esp` plugin, as error code 5 is a parsing error. I googled the plugin name and the first result was a [fixed version](https://www.nexusmods.com/skyrim/mods/85193) someone had made ("No more LOOT / TES5Edit / Wyre Crashes."), so maybe try that?

**Comment by igotsometrouble** [comment]
this worked like a charm. Thanks for your help, I had no idea about what to look for after you said the others were important I went through all the debuglog still couldent notice anything so thanks again.
