### ISSUE TITLE
Not able to access Masterlist

### ISSUE THREAD

**Issue by DJWolf1** [loot/skyrim#169]
When I load loot I get the following error:

"An error occurred while parsing the metadata list(s): yaml-cpp: error at line 201, column 13: bad conversion: 'text' key missing from 'message content' object.
Try updating your masterlist to resolve the error. If the error is with your user metadata, this probably happened because an update to LOOT changed its metadata syntax support. Your user metadata will have to be updated manually.
To do so, use the 'Open Debug Log Location' in LOOT's main menu to open its data folder, then open your 'userlist.yaml' file in the relevant game folder. You can then edit the metadata it contains with reference to the documentation, which is accessible through LOOT's main menu."

And, of course I cannot sort my mods.

I haven't played Skyrim for two years and I was using Loot back then with NMM.  Four days ago I downloaded MO and installed the most recent version of Loot (to operate within MO) and began building a mod set up which uses almost none of the mods I used before.  However, looking at the top of the Loot page I read, "Masterlist Date:  2016-02-04" and I need nothing from that list of mods."

While I found a "settings.yaml" and even a "masterlist.yaml", I could find no "userlist.yaml"

So, I'm stuck here waiting to sort and then play.  I look forward to hearing from you.

**Comment by Ortham** [comment]
What happens if you try updating the masterlist?

**Comment by DJWolf1** [comment]
I get a message that starts with "Oops"  I can't remember the rest

**Comment by DJWolf1** [comment]
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information

**Comment by Ortham** [comment]
Please [attach your debug log](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by DJWolf1** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1752240/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
You're getting the same error as in loot/loot#882, install the fix linked to in that issue thread then try again.

**Comment by DJWolf1** [comment]
Unfortunately, it did not work.  I downloaded the fix from Microsoft, launched MO again and ran Loot with the same result.  What I haven't tried iss rebooting my machine which I will do now.

**Comment by DJWolf1** [comment]
No I still have the same red warning.  However, when trying to update my Masterlist I got the same or a similar warning but I at least got a recent masterlist  (by the date).  I also got information on the dirty edits on the master files which wasn't there before.

**Comment by DJWolf1** [comment]
As an afterthought, I decided to sort my mods anyway...  Lo and behold the warning disappeared.

Thank you, WN.  Really.  Helping a stranger like you have done.  It doesn't get better than that.  Thank you.
