### ISSUE TITLE
No Master list

### ISSUE THREAD

**Issue by BorisYelzin321** [loot/skyrim#171]
I love Loot and it's functionality, but i have recently a problem with my masterlist update.
I have no firewall with my AV.

[CEFDebugLog.txt](https://github.com/loot/skyrim/files/1752879/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1752880/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
This is a duplicate of loot/loot#882.
