### ISSUE TITLE
MASTERLIST NOT LOADING error message

### ISSUE THREAD

**Issue by Japamam** [loot/skyrim#172]
Since yesterday my loot downt owrk properly givng a error message when i try to sort. There is the log plz help.
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1753640/LOOTDebugLog.txt)

**Comment by Japamam** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1753677/LOOTDebugLog.txt)
This one is more complete, same error

**Comment by Ortham** [comment]
This is a duplicate of loot/loot#882.
