### ISSUE TITLE
Cant load master-list into loot and cannot sort master-list. 

### ISSUE THREAD

**Issue by Virgo10** [loot/skyrim#174]
I have tried to reinstall LOOT, I have tried sorting just the master list, I have tried whitelisting it from my AV, I have tried deleting the Skyrim map and re-running it. I have tried making it run via admin. I have tried most of what I can find online. I don't know what to do. It just randomly stopped working yesterday. It couldn't sorta my master list, then I reinstalled, and now it cant find my master list. 

I apologize if I am putting this is the wrong spot and wrong # etc. Thank you for your time.

[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1755714/LOOTDebugLog.txt)

**Comment by SuperSandro2000** [comment]
https://github.com/loot/loot/issues/882

**Comment by pStyl3** [comment]
Update LOOT to version 0.12.4, install all recommended Windows updates and make sure that you [enable TLS 1.2 support](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) to support updating the masterlists from LOOT's official repositories on GitHub.

**Comment by Virgo10** [comment]
The "Quick Fix" fixed it! Thank you! <3 :D
