### ISSUE TITLE
plugins.txt is not Read only, but still getting message to uncheck it.

### ISSUE THREAD

**Issue by nuclearchurro** [loot/skyrim#180]
I launched LOOT for the first time today after a while, it bugged out and messed up my load order, causing CTD on any load or new game. I then updated LOOT and I am now getting the error that I need to uncheck "Read only" for the plugins.txt, when it is already unchecked.

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).
