### ISSUE TITLE
Cyclic Interaction Detected (Skyrim Unlocked and Alternate Start - LAL)

### ISSUE THREAD

**Issue by ColossusX13** [loot/skyrim#184]
Failed to sort plugins. Details: Cyclic interaction detected between "Requiem - Skyrim Unlocked.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Hold Borders LAL Pathfinding Patch.esp, Skyrim Unlocked.esp, Requiem - Skyrim Unlocked.esp

This is without any metadata added my me

**Comment by Ortham** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by ColossusX13** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/2065339/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Try setting `Hold Borders LAL Pathfinding Patch.esp` or `Requiem - Skyrim Unlocked.esp` to be in the `Alternate Start` group using the metadata editor.

**Comment by ColossusX13** [comment]
Putting Requiem - Skyrim Unlocked.esp in the Alternate Start group worked, thanks for the help.

**Comment by Ortham** [comment]
OK, I've added that to the masterlist.
