### ISSUE TITLE
LB_MuchAdoSnowElves.esp doesn't require lady body and vice versa

### ISSUE THREAD

**Issue by Freso** [loot/skyrim#197]
@feeddanoob [wrote](https://github.com/loot/loot/issues/993#issue-349669627):
> LB_MuchAdoSnowElves.esp for classic skyrim doesn't require lady body and vice versa. I'm not sure how this was missed.

**Comment by pStyl3** [comment]
Done as of https://github.com/loot/skyrim/commit/adcb685b041c1419d2e0dfd5e88ec7bb401aedad.
