### ISSUE TITLE
Crashing in Mod Organizer

### ISSUE THREAD

**Issue by ChiefZigZag** [loot/skyrim#22]
I had crashing in Mod organizer.. however when I changed the header for the EXE to utilize address space above 2GB it worked fine.

Cheers

**Comment by Dyscrasite** [comment]
Loot 6 has been crashing on me as well when I run it from MO. I thought it was a corrupted plugin so I deleted and reinstalled them but still got crashes from Loot.
It doesn't crash all the time but maybe 10% - 20% of the time....

Just trying to find a way to stop the crashing.

**Comment by WrinklyNinja** [comment]
> Loot 6 has been crashing on me as well when I run it from MO. I thought it was a corrupted plugin so I deleted and reinstalled them but still got crashes from Loot.
> It doesn't crash all the time but maybe 10% - 20% of the time....
> 
> Just trying to find a way to stop the crashing.

This isn't the right place for this issue, you want the [loot/loot](https://github.com/loot/loot/issues) issue tracker. IIRC I fixed quite a few potential crashes in v0.7, does the beta work for you?
