### ISSUE TITLE
The Brotherhood of Old

### ISSUE THREAD

**Issue by VincentIgnition** [loot/skyrim#222]
I would like to have my mod added to the Skyrim LE and SSE masterlists but I've never done it before and don't want to mess anything up. I've looked through the documentation but I really don't know what I'm doing here. Could someone add it for me? Here are the URLs for the mod:

[Special Edition](https://www.nexusmods.com/skyrimspecialedition/mods/15322)
[Legendary Edition](https://www.nexusmods.com/skyrim/mods/89857)

I want to add it to the masterlists because there is a conflict where if Immersive Citizens is loaded after The Brotherhood of Old, some of my NPCs won't talk to you or they just disappear. The apparent fix for this according to some of my players is placing Immersive Citizens before The Brotherhood of Old in your load order, but LOOT is not doing this automatically.

Thanks.

**Comment by MacSplody** [comment]
@tomtesoro SSE Version is done.

**Comment by MacSplody** [comment]
@tomtesoro Done for LE as well.

**Comment by VincentIgnition** [comment]
Thanks for your help @CptMcSplody . I've recently cleaned the mod with xEdit 4.0 and was wondering if I could get the verified clean icon back?
