### ISSUE TITLE
Loot showing more ITMs than Being Cleaned by TES5edit

### ISSUE THREAD

**Issue by OkamiRyu92** [loot/skyrim#230]
So during my reinstallation of skyrim from the ground up (deleted EVERYTHING pertaining to skyrim/steam) I went to start cleaning the files after I have successfully downloaded and installed everything that I'll be working with. 

SO here's the issue. and this can be reproduced indefinitely as far as I can tell.

Here are what I am running:

Loot 13.6
TES5Edit 4.0.1

Using these files as problem files
Skyrim.esm
Hearthfires.esm

Now when I load loot first, it shows that I have 231 itms. (everything else is cleaned correctly)
But when it's cleaned, it only removes 184, leaving me with another 47 that seem to have just "poofed" out of existence because when I sort again, the warning message disappears.

Anyone know why this is?

**Comment by OkamiRyu92** [comment]
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/2722845/LOOTDebugLog.txt)

This is my debuglog for today

**Comment by MacSplody** [comment]
@OkamiRyu92 Hi, did you read the linked guide?
https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html#quickautoclean

**Comment by OkamiRyu92** [comment]
I did as the guide suggested, but for some reason it is not performing the cleaning.

**Comment by MacSplody** [comment]
![image](https://user-images.githubusercontent.com/1944639/50667472-5d45e300-0fb1-11e9-8177-6a68ef3ba39e.png)

That's the output I'm getting for `-quickautoclean`

![image](https://user-images.githubusercontent.com/1944639/50667705-78fdb900-0fb2-11e9-8b41-1609bb5f2c8b.png)
and `-quickclean`

**Comment by MacSplody** [comment]
Check the file `crc` after cleaning `0x3598AD26`, you'll see it in LOOT after sorting.

**Comment by OkamiRyu92** [comment]
how did you get tes5 to show that?

**Comment by OkamiRyu92** [comment]
can you join their discord server so we can do this real time?

**Comment by MacSplody** [comment]
@OkamiRyu92 If you're running `-quickautoclean` it does it automatically.

**Comment by Sharlikran** [comment]
First you need the latest version which is 4.0.1 or higher. Then you need to add the parameter correctly.

I see people saying it's not working but that seems to be becaue people don't know what a shortcut is or how to edit them. If there are spaces that seems to complicate things more.

For shortcuts you can easily Google that. I did just to see how easy I could find instructions and there were many useful links.
