### ISSUE TITLE
Load Order Issue - Deadly Spell Impacts and Immersive Sounds

### ISSUE THREAD

**Issue by Squirrelydood** [loot/skyrim#243]
LOOT forces Immersive Sounds to load after Deadly Impacts despite there being a patch that invalidates that load order requirement (and is prompted by LOOT to download), this becomes an issue when needing to load Deadly impacts after other mods that overwrite it but would cause issues with immersive sounds overwriting other information later in the load order.

**Comment by MacSplody** [comment]
@Squirrelydood Can you provide links to these other mods that deadly spell impacts needs to load after?

**Comment by Squirrelydood** [comment]
Skyrim
https://www.nexusmods.com/skyrim/mods/54387/
https://www.nexusmods.com/skyrim/mods/2947

Skyrim SE
https://www.nexusmods.com/skyrimspecialedition/mods/523?tab=description
https://www.nexusmods.com/skyrimspecialedition/mods/12939

**Comment by MacSplody** [comment]
> 
> 
> Skyrim
> https://www.nexusmods.com/skyrim/mods/54387/
> https://www.nexusmods.com/skyrim/mods/2947
> 
> Skyrim SE
> https://www.nexusmods.com/skyrimspecialedition/mods/523?tab=description
> https://www.nexusmods.com/skyrimspecialedition/mods/12939

That's just Immersive Sounds and deadly Spell impacts. I was referring to
>this becomes an issue when needing to load Deadly impacts after **other mods** that overwrite it

What other mods? it would be useful to know these.

**Comment by Squirrelydood** [comment]
I still use the removed from nexus mod NSO and NSO - Magic which merge a lot of other mods into a large overhaul, so one or more of those mods caused edits to the impact data that conflicted with both. In either case the Patch renders the meta data useless and the current loadafter meta data means that if for whatever reason you don't use the patch (such as running low on plugin space) Immersive sounds will overwrite nearly all the data of Deadly Spell Impact where as DSI will only overwrite a small bit of the larger sound overhaul.

**Comment by MacSplody** [comment]
> NSO and NSO - Magic

Well I have no way to test those mods, so I'll take your word for it.

> In either case the Patch renders the meta data useless and the current loadafter meta data means that if for whatever reason you don't use the patch (such as running low on plugin space) Immersive sounds will overwrite nearly all the data of Deadly Spell Impact where as DSI will only overwrite a small bit of the larger sound overhaul.

The reason the rule was added is that there was no patch at the time, and the following compatibility info provided on the Deadly Spell Impacts mod page.

> Compatible with all mods. Load order doesn't matter.

There is a change for Deadly Spell Impacts already in the next SSE Masterlist Update.
https://github.com/loot/skyrimse/pull/608/commits/ca73838b6d91e48f29ec4f7c916fd45ac5be0de3
The changes are as follows:

Load after `Deadly Spell Impacts.esp` for are removed from Immersive sounds and Audio Overhaul.
`Deadly Spell Impacts.esp` is placed in a group before both Immersive sounds and Audio Overhaul.

This means it will sort before both by default, but can be changed by the user with an after rule or by changing `Deadly Spell Impacts.esp` group to one after both Immersive sounds and Audio Overhaul.

`Deadly Spell Impacts.esp` will also load after both if a patch is present for both.
The patch does not need to be active, just in the data folder.

I'll keep this open as a reminder to implement the change for LE.

**Comment by Squirrelydood** [comment]
That change does not appear to be in the SE loot, it still forces Immersive Sounds to load after Deadly Spell Impacts (https://i.imgur.com/vwlVqvO.png), and again this load after basically cripples the much smaller mod overwriting about 40 out of 60 Records where it only overwrites 40 out of 2000 records and should not have a forced load after regardless.

**Comment by MacSplody** [comment]
> There is a change for Deadly Spell Impacts already in the **next** SSE Masterlist Update.

**Comment by pStyl3** [comment]
> There is a change for Deadly Spell Impacts already in the next SSE Masterlist Update.
> [loot/skyrimse@ca73838](https://github.com/loot/skyrimse/commit/ca73838b6d91e48f29ec4f7c916fd45ac5be0de3)

> I'll keep this open as a reminder to implement the change for LE.

Could we have this added to SLE's masterlist aswell @CptMcSplody ?

**Comment by MacSplody** [comment]
Just tested it and default sorting places `DeadlySpellImpacts.esp` after both `Immersive Sounds - Compendium.esp` and `AOS.esp` for SLE.
There are no patches available for the three mods like SSE.
This issue was more to do with the SSE rules anyhow.
I think it's just safer to leave it as is for LE, so I'm going to just close this issue.
