### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by itsmegenetics** [loot/skyrim#244]
This is my first time using LOOT via MO and i followed the guide in reddit. It worked one time when i was sorting out the plugin but now it wont and no changes will be made. 
Hoping for some help. Thanks

[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/2904481/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
```
[16:28:19.381473] [error]: Exception while executing query: Repository path, URL and branch must not be empty.
```

Your settings are invalid, try fixing them. If you don't know what to set them to, delete `%LOCALAPPDATA%\LOOT\settings.toml` and relaunch LOOT.

**Comment by MacSplody** [comment]
@itsmegenetics Any update on this, did you resolve the issue?
