### ISSUE TITLE
stonhenge + hilltops.esp UDR cleaning report

### ISSUE THREAD

**Issue by potens1** [loot/skyrim#267]
- name: 'stonhenge + hilltops.esp'
    dirty:
      - <<: *quickClean
        crc: 0x773331D4
        util: '[SSEEdit v4.0.2](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 8
    clean:
      - crc: 0x29F6D931
        util: 'SSEEdit v4.0.2'

**Comment by pStyl3** [comment]
Is that [this](https://www.nexusmods.com/skyrimspecialedition/mods/9731) Skyrim Special Edition mod?

**Comment by pStyl3** [comment]
Closed as of https://github.com/loot/skyrimse/pull/763/commits/889dd2ce82486a94da9327e3685a69328f0dedbf.

Please note, that this is the Skyrim masterlist, not the masterlist for Skyrim Special Edition. That one can be found [here](https://github.com/loot/skyrimse).

**Comment by potens1** [comment]
@pStyl3 sorry, indeed it was for the SE mod, my mistake.
