### ISSUE TITLE
Skyrim metadata issue.

### ISSUE THREAD

**Issue by Elaura1970** [loot/skyrim#287]
![2019-09-22 06_30_27-Window](https://user-images.githubusercontent.com/21957591/65386552-e7320980-dd02-11e9-9f87-ce7886f743bd.png)

As you see in the left pane, the mod patch LOOT is suggesting is already in my load order. The file is from the suggested link.

**Comment by pStyl3** [comment]
I'll take a look. The data for this mod was recently updated, so chances are something was overlooked.

**Comment by Elaura1970** [comment]
Cool, thanks!

**Comment by pStyl3** [comment]
@Elaura1970 Please update your masterlist. Can you confirm if the issue is fixed?
