### ISSUE TITLE
Cycle between mods included in STEP

### ISSUE THREAD

**Issue by TanninOne** [loot/skyrim#290]
I think the current masterlist creates a cyclic interaction between
a) STEP Core Patch.esp (in group Step Patches & Skyrim Child Overhaul)
b) Skyrim Unbound.esp (in group Alternate Start & Requiem)
c) ELE_Legendary_Lite.esp (in group Lighting)

Group Lighting is set to load after Skyrim Unlocked after Alternate Start & Requiem after Open Cities Skyrim after Requiem after Morrowloot after Step Patches & Skyrim Child Overhaul

which would place c after a but a has c as a master.

**Comment by pStyl3** [comment]
I've updated the cleaning data for Skyrim Unbound and added the location url for STEP Core Patch as a first step. https://github.com/loot/skyrim/commit/95d7cdfdfa3890eb9f80c41d32ecfb6db67dd33b

As for the described issue, I will need to check that in more detail. To note is, that there are two versions of the ELE plugin.

ELE_Legendary_Lite.esp - Normal Version - Masters
```
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Unofficial Skyrim Legendary Edition Patch.esp
```

ELE_Legendary_Lite.esp - STEP Version - Masters
```
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
```

And there are four different versions of `STEP Core Patch.esp`: Normal, No ELE, No ELE & No ICAIO and No ICAIO. The "normal" version has the following masters:
```
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Unofficial Skyrim Legendary Edition Patch.esp
ELE_Legendary_Lite.esp
Cutting Room Floor.esp
Guard Dialogue Overhaul.esp
Invisibility Eyes Fix.esp
ExplosiveBoltsVisualized.esp
aMidianBorn_ContentAddon.esp
Elemental Staves.esp
ADS.esp
Immersive Citizens - AI Overhaul.esp
RealisticWaterTwo.esp
AOS.esp
Vividian - Extended Weathers.esp
```

**Comment by pStyl3** [comment]
More preparatory actions: https://github.com/loot/skyrim/commit/b64156feaf3a0cdb5bd5c607f1e4334456e45a86

**Comment by MacSplody** [comment]
Just a note, but a cycle is more likely to happen when:
1) A mod is in a group after **_default_**.
2) One of its _masters_ is in a higher group.
3) The _masters_ group is not directly after the mods own group.

In the above case `STEP Core Patch.esp` is having a cycle with all the mods in groups between it and its highest master. In this case iirc it's `ELE_Legendary_Lite.esp`.

**Comment by pStyl3** [comment]
https://abload.de/img/cyclicinteractionkhknl.png

I can reproduce the issue with the normal version (crc: 0x2AB0D55B) of `STEP Core Patch.esp` and the No ICAIO version (crc: 0x297C8EE2). I can NOT reproduce the issue with the No ELE version (crc: 0x0182E9FA) and the No ELE / No ICAIO version (crc: 0xE2D08AF8) of `STEP Core Patch.esp`.

It doesn't seem to matter, which of the two versions of `ELE_Legendary_Lite.esp` is used.

**Comment by MacSplody** [comment]
> In the above case `STEP Core Patch.esp` is having a cycle with all the mods in groups between it and its highest master.

![image](https://user-images.githubusercontent.com/1944639/65795501-5a53d980-e162-11e9-87b4-9044e1099da5.png)

You could replicate it with any mod in those groups if they aren't a master for `STEP Core Patch.esp`, or ELE isn't set to load after them.

You could fix it a few ways, easiest is to move `STEP Core Patch.esp` to the **_default_** group.
Or make sure ELE is set to load after `Skyrim Unbound.esp`.

**Comment by pStyl3** [comment]
Done in https://github.com/loot/skyrim/commit/0b16d19199497ed1f3c3ff5b483129a3dd7bc226
