### ISSUE TITLE
Load order for ELFX and AnnaBreezeHome

### ISSUE THREAD

**Issue by TsukiDragon** [loot/skyrim#321]
Per [Enhanced Lights and FX](https://www.nexusmods.com/skyrim/mods/27043), any Player home .esp (in this case [Anna Breezehome](https://www.nexusmods.com/skyrim/mods/98976)) should be placed after ELFX -No Breezehome.esp. Current load order places it above it and causes many lights to be out of place.

**Comment by sibir-ine** [comment]
@TsukiDragon Done, thanks for the report!
