### ISSUE TITLE
Need help with my loot (new to modding btw and thanks in advance!)

### ISSUE THREAD

**Issue by G0dli** [loot/skyrim#351]
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/4112302/LOOTDebugLog.txt)

**Comment by MacSplody** [comment]
> 
> 
> [LOOTDebugLog.txt](https://github.com/loot/skyrim/files/4112302/LOOTDebugLog.txt)

What's the issue you're having?

**Comment by MacSplody** [comment]
Closing as there's no problem stated.
