### ISSUE TITLE
Reevaluation and Refactor of unaliased TES5 messages

### ISSUE THREAD

**Issue by pStyl3** [loot/skyrim#452]
Similar issue for the Oblivion masterlist: loot/oblivion#311

The Skyrim masterlist does contain a lot of unaliased messages, that do not make use of message anchors in the form of `&example` yet.

A good amount of messages can likely stay as they are, but other messages can evenly likely be refactored to use existing (or to be created) message anchors, or even be removed because they are outdated or the plugin in question is not locatable in any way.

Because of the sheer amount of plugins that have such messages assigned to them, this issue will only serve as the central hub to organize and link all individual issues, that will be opened to handle this. These issues will "group" plugin messages that are similar, to make it easier for us to reach conclusions as to what to do with them.

While working on this, it will likely be the best course of action, to always add missing `url`'s, in case plugins are missing them. Try your best to locate plugins, if the masterlist does not yet contain an `url` for the plugin in question. But if the plugin in question seems unlocatable, it will be reasonable to remove the plugin in question as a whole.

These issues will need to be resolved:
- [x] #456
- [x] #453
- [x] #457
- [x] #461
- [x] #459
- [x] #454
- [x] #455
- [x] #458
- [x] #460

**Comment by sibir-ine** [comment]
As with the TES4 issue, this would be a good opportunity to sort the plugins we work on into sections. SLE currently only has 3 sections (`Official Game Files`, `Unofficial Patches`, & `Modding Tools - Generated Files`), but we can add the sections in the SSE & TES4 masterlists when needed.

**Comment by pStyl3** [comment]
Thanks a lot @sibir-ine, great work! 🎉
