### ISSUE TITLE
Beyond Skyrim - Bruma, and Beyond Reach load order fix

### ISSUE THREAD

**Issue by Darklocq** [loot/skyrim#475]
BSHeartland.esm from "Beyond Skyrim - Bruma" has to load after arnima.esm from "Beyond Reach", or the patch between them - available here: [https://www.nexusmods.com/skyrim/mods/85579](https://www.nexusmods.com/skyrim/mods/85579) - cannot work. For tidiness sake, it might be better to tell BSAssets.esm to load after arnima.esm, since BSHeartland.esm loads after the former. That would keep Beyond Skyrim ESMs together.

**Comment by sibir-ine** [comment]
@Darklocq From looking at the mods in xEdit, order shouldn't really matter between the two. The only difference it makes is that if `BSHeartland.esm` is loaded after `arnima.esm`, it actually undoes some region changes to a cell that `arnima.esm` forwards from `Dawnguard.esm` that were accidentally undone by `HeathFires.esm` & `Dragonborn.esm`.

The only other thing of note is that `BSHeartland.esm` changes the NAM0 & NAM9 subrecords of the Tamriel worldspace, which `BSHeartland - Arnima Patch.esp` attempts to undo anyway. However, these changes in particular appear to actually [merge at runtime](https://www.afkmods.com/index.php?/topic/3940-skyrim-tes5edit-records-that-merge-at-runtime/) regardless of load order. From a brief search of the Beyond Skyrim description & forum, I couldn't find any mention of this change, so it could be unintentional & cause problems in-game.

Have you actually experienced the invisible buildings that the patch description mentions from LOOT's default sorting? If so, try undoing the NAM0 & NAM9 changes I previously discussed. They seem to make the cell dimensions of the Tamriel worldspace significantly smaller, so maybe that's causing the issue.

**Comment by Darklocq** [comment]
Not something I directly experienced. I was taking the patch author at their word that the load order was important.

**Comment by sibir-ine** [comment]
Maybe the advice applied to an older version of the patch. For now though, it doesn't appear that a load rule is necessary. Feel free to reopen this or file a new issue if something changes.
