### ISSUE TITLE
Immersive Sounds - Compendium, and other sound mods - order

### ISSUE THREAD

**Issue by Darklocq** [loot/skyrim#478]
ISC is a general, sweeping, and kind of scattershot sound overhaul, like Audio Overhaul for Skyrim and Sounds of Skyrim Complete.

It should load before very specific sound-change mods; if anyone is installing one of those over ISC (or AOS or SSC) it's because they want to fine-tune those specific sounds.

Load-order problems I've detected so far are that all of the following are loaded by LOOT before ISC, and should be after it:

NSM Low.esp, NSM Regular.esp, NSM Loud.esp, NSM Silient.esp (mutually exclusive variants)
Nirnroot Sound Modification
https://www.nexusmods.com/skyrim/mods/46245

There are lots of other "tweak the Nirnroot" mods, but NSM Low is the one I'm using.

BWS.esp
Better Weapon Swing Sounds
https://www.nexusmods.com/skyrim/mods/17903

On the up side, lots of other sound mods like "Smooth Blade Draw and Sheath" and "IHSS - Improved Horse Step Sounds" are loading after ISC.

**Comment by sibir-ine** [comment]
The mods you linked are just dummy plugins that load BSAs. Seeing as ISC uses loose files, load order doesn't matter in any of these cases, though none of their files conflict anyway.
