### ISSUE TITLE
Requiem load order incorrect

### ISSUE THREAD

**Issue by Vultraz** [loot/skyrim#51]
LOOT insists on placing Requiem near the top of the masterlist, and the Requiem for the Indifferent patch after the Bashed Patch. The Requiem manual recommends Requiem being placed immediately before the Bashed Patch (but before patches such as the AOS Requiem patch), and the RftI skyproc patch after the BP.

**Comment by egocarib** [comment]
We don't usually enforce absolute plugin positions (such as "after everything else" or "immediately before the bashed patch"). Ordering rules are usually added to the master list only for confirmed record conflicts between specific plugins. Often for a major game overhaul like requiem you'll want to add some user rules to reorder things for yourself, but if there is a specific conflict that causes errors please feel free to report it.
