### ISSUE TITLE
Load Verdant after Skyrim Flora Overhaul

### ISSUE THREAD

**Issue by RadioactiveStud** [loot/skyrim#59]
"Verdant - A Skyrim Grass Plugin.esp" should load after any esps from "Skyrim Flora Overhaul" or Skyrim may crash while outdoors.
According to the Verdant mod page (http://www.nexusmods.com/skyrim/mods/60220):
> Load this AFTER SFO and any other mods that alter the landscape, specifically mods that add grasses to the game.

It also states:
> So apparently LOOT is loading my plugin BEFORE SFO 2.0+ but THAT IS NOT CORRECT. You must make a custom rule in your loot order to load Verdant after, or adjust it manually in your load order for this mod to work properly!!

I can confirm Skyrim does crash if you load them in the wrong order.

**Comment by LuthienKess** [comment]
This issue was corrected by [this](https://github.com/loot/skyrim/commit/77a08fd82b555a52aba1266e728475d5f0bf1d58) update and can be closed.

**Comment by WrinklyNinja** [comment]
OK, thanks.
