### ISSUE TITLE
Load order: Arthmoor's Villages (or Keld Nar) AFTER Clockwork

### ISSUE THREAD

**Issue by Darklocq** [loot/skyrim#641]
"[Arthmoor's Skyrim Villages - All In One](https://www.afkmods.com/index.php?/files/file/2111-arthmoors-skyrim-villages-all-in-one/)"

and his stand-alone "[Keld Nar](https://www.afkmods.com/index.php?/files/file/2038-keld-nar/)" village

need to load AFTER...

"[Clockwork (Clockwork Castle)](https://www.nexusmods.com/skyrim/mods/77809)" [not to be confused with "The Clockwork Adventure"]

Otherwise there are massive landscape tears and other badness, because Clockwork's Velothi Tunnel entrance collides with a manor in the village of Keld Nar (a town that required a lot of landscape tweaking).

Even with the right load order they still require a [patch](https://www.nexusmods.com/skyrim/mods/110574) (to avoid overlapping doors), and it has been made.

In quick searching around, I'm not finding an SE version of AV.  Arthmoor's only content for SE seems to be the Unofficial Patch.  Clockwork does exist for SE, so if someone ports AV, then a patch will also need to be ported.  Nothing LOOT for SE needs to worry about right now.

**Comment by sibir-ine** [comment]
You accidentally linked to the SSE page for Keld-Nar, so I've corrected that (& hyperlinked the links for better readability). However, the SLE version doesn't include a patch for Clockwork (whereas the SSE version does), so it looks like we'll have to note that a patch for the two isn't currently available for download. The rule for the AIO mod & Clockwork can be added though.

**Comment by sibir-ine** [comment]
@Darklocq Thanks for the report!
