### ISSUE TITLE
Deleted Navmesh Messages Should Be Cleaned Up

### ISSUE THREAD

**Issue by egocarib** [loot/skyrim#67]
### Overview
Deleted navmesh messages take up a very large amount of space in the masterlist right now, and we should try to reduce or eliminate those messages where possible.

The masterlist currently contains 192 plugins with deleted navmesh messages.
* Only 12 of these messages are conditioned to a specific CRC. 
* However, 174 of the 192 plugins include a dirty info structure with at least 1 CRC listed.

### Possible Solution
The `dirty` info structure is already designed to include a `nav:` key that should list the number of deleted navmeshes. Using this key more consistently would eliminate the need to have deleted navmesh messages altogether. However, the `nav:` key is very underutilized. It currently appears only 12 times in the masterlist.

After chatting with WrinklyNinja, I think the best strategy is to remove existing navmesh messages for any plugin where a dirty CRC is also listed, and just add a `nav:` key to that existing dirty info structure that indicates the number of deleted navmeshes that were specified in the message. Because dirty info and navmesh info are usually reported together, it seems very likely that the existing navmesh messages correspond to the existing dirty CRCs. There's a small chance that this change could introduce some erroneous info into the masterlist, but if that happens, a user is likely to report the issue once the error is discovered.

##### Missing CRCs
Any mods with a deleted navmesh message that do not also have a dirty info structure should be listed here so that they can be followed up on. We should try to find the CRCs for these mods so that we can incorporate their navmesh information into a dirty info structure and keep things standardized across the masterlist.

##### Improved Tutorial Links
We should also add a link to the &dirtyUtil anchor that will redirect users somewhere that they can learn about fixing deleted navmesh records. We currently link to [this tutorial](http://www.iguanadons.net/Skyrim-Fixing-Navmesh-Deletion-Using-TES5Edit-511.html). Wrinkly suggested that we could make some improvements to the [TES5Edit Cleaning Guide](http://www.creationkit.com/TES5Edit_Cleaning_Guide_-_TES5Edit), and include some more prominent links from that guide to videos and tutorials for cleaning itms, udrs, and deleted navmesh records. We could then update the &dirtyUtil anchor something like this:

```
 - &dirtyUtil
    '[TES5Edit](http://www.nexusmods.com/skyrim/mods/25859). A cleaning guide is available [here](http://www.creationkit.com/TES5Edit_Cleaning_Guide_-_TES5Edit)'
```

**Comment by WrinklyNinja** [comment]
Regarding the tutorial links, here are some relevant pages:

* [TES5Edit Nexus page](http://www.nexusmods.com/skyrim/mods/25859): There are some cleaning tutorial videos embedded there.
* [Navmesh tutorial on the CK Wiki](http://www.creationkit.com/Fixing_Navmesh_Deletion_Tutorial): I copied it from Arthmoor's site.
* [Cleaning tutorial on the CK Wiki](http://www.creationkit.com/TES5Edit_Mod_Cleaning_Tutorial)
* [Mod cleaning page on LOOT's wiki](https://github.com/loot/loot.github.io/wiki/Dirty-Edits%2C-Mod-Cleaning-%26-CRCs)

**Comment by WrinklyNinja** [comment]
This has now been done as of #95 and my CK wiki edits.
