### ISSUE TITLE
Turn requirement messages into proper metadata

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/skyrim#70]
What it says on the tin. Currently offending entries are:
- [x] `LiFE.esm`
- [x] `Malise - A Companion By Joseph Anthony.esm`
- [x] `Alexia CatGarter.esp`
- [x] `ArmoredNocturnal.esp`
- [x] `Backpack OE.esp`
- [x] `BBP_ArmorPack2.esp`
- [x] `Bikini Clothes.esp`
- [x] `bikiniADEC.esp`
- [x] `bikiniCHSBHC.esp`
- [x] `Casual Outfit OE.esp`
- [x] `chainmail.esp`
- [x] `ChildrenClothesClassed.esp`
- [x] `CraftableCrownHelmets.esp`
- [x] `selobl_DarkLillith.esp`
- [x] `DemonHunterV2armor.esp`
- [x] `DHuntress.esp`
- [x] `DIMclothes1.esp`
- [x] `Doom Heavy Set.esp`
- [x] `FlameAtronachArmor.esp`
- [x] `Fitness Outfit OE.esp`
- [x] `Footwear OE.esp`
- [x] `frost armour.esp`
- [x] `FullBootForKKSA.esp`
- [x] `NordicSkaalHeavyFalmerWeightFix.esp`
- [x] `GattiBondage0.esp`
- [x] `GattiBondage1.esp`
- [x] `HmmWhatToWear.esp`
- [x] `Ice Armour.esp`
- [x] `Juquinha-armory.esp`
- [x] `KURESE Gloria conversion.esp`
- [x] `Lady of Death.esp`
- [x] `LBArmorPack.esp`
- [x] `LB Blood Mage.esp`
- [x] `Blood Mage.esp`
- [x] `LB Ярл Clothes.esp`
- [x] `LB Blood of the Divines.esp`
- [x] `LB Dark Lady.esp`
- [x] `LB Dragon Princess.esp`
- [x] `LB Dwemer Fury Heavy Set.esp`
- [x] `LB GoldLeopardRobe.esp`
- [x] `LB Jarl Clothes.esp`
- [x] `LB Lady Bat.esp`
- [x] `LB Lady Keaira.esp`
- [x] `LB Lady .+\.esp`
- [x] `LB Lustmord Vampire.esp`
- [x] `LB Lydia Armor.esp`
- [x] `LB Mandu Armor.esp`
- [x] `LB Medusa Armor.esp`
- [x] `LB_MuchAdoSnowElves.esp`
- [x] `LB Necromance Robe.esp`
- [x] `LB Pantie & Boots.esp`
- [x] `LB Jewelry.esp`
- [x] `LB RobeExperiencedMagician.esp`
- [x] `LB Santa Babe.esp`
- [x] `LB Underworld.esp`
- [x] `LB Valkyrie.esp`
- [x] `LB VampLord.esp`
- [x] `LBClosetMagician.esp`
- [x] `LBGoldArmoredBikini.esp`
- [x] `LC_AssassinOfShadownArmor.esp`
- [x] `LeiFangAndChristieByNausicaa.esp`
- [x] `LH Jewel Collection.esp`
- [x] `MinaArmors.esp`
- [x] `Mini Sage Outfit.esp`
- [x] `Osare KneeSocks.esp`
- [x] `Osare Maid Outfit.esp`
- [x] `PENIS.esp`
- [x] `Guard Weapons - Heavy Armory - Halberds.esp`
- [x] `RogueOutfit.esp`
- [x] `Saber Lily - Caliburn Outfit.esp`
- [x] `seducesets.esp`
- [x] `SED7-CBBE3.+\.esp`
- [x] `SED7-BettermalesFLACID_SILVEREDITION_malePiercing_PA.esp`
- [x] `selobl_Diano.esp`
- [x] `Skimpy Plate Armor.esp`
- [x] `Spriggan Armor 2.esp`
- [x] `Strapless Bikinis.esp`
- [x] `SuccubusUNPByNausicaa.esp`
- [x] `TBSC_BodySuit.esp`
- [x] `TERAArmors_CBBE.esp`
- [x] `TeraArmors-CBBEByNausicaa.esp`
- [x] `TERAArmors.esp`
- [x] `TERA Armors for Skyrim - UNP.esp`
- [x] `TERA Armors for Skyrim - UNPB-BBP.esp`
- [x] `TMasks-JudgmentDay.esp`
- [x] `UNP Jewelry Retextured.esp`
- [x] `UNP Jewelry Variants V-2.esp`
- [x] `UNP Leather Clothes.esp`
- [x] `UNP Boots.*\.esp`
- [x] `UNP Undies.esp`
- [x] `UNPB Barbarian Armor.esp`
- [x] `UNP Petrovna.esp`
- [x] `ViceroyInquisitor.esp`
- [x] `RecyclingModWo3E.esp`
- [x] `YPSArmorPack.esp`
- [x] `zzTmBallGown.esp`
- [x] `ERSO 03 - (Nightmare |Slighty |Super )?Mighty Dragons( Unleveled)?( plus)? DD\.esp`
- [ ] `SkyRe_Main.esp`
- [ ] `SkyRe_Main_NoDawnguard.esp`
- [x] `SkyRe_Plugin_Omegared99sArmorCompilation.esp`
- [x] `SkyRe_Plugin_Omegared99sArmorCompilation_3.esp`
- [x] `Sweet&Sexy Lingerie.esp`
- [x] `Better Warzones Soldier Uniforms.esp`
- [x] `Better Warzones Soldier Uniforms With Cloaks.esp`
- [x] `BetterQuestObjectives-BSaQBPatch.esp`
- [x] `DA_Maxwell_Outfit_Dibella_UNP.esp`
- [x] `DA_Maxwell_Outfit_Dibella_UNP_EV.esp`
- [x] `RSkyrimChildren.esm`
- [x] `LB Yarl Clothes.esp`
- [x] `PalistovSpinningArrows_CloserQuiversLongerArrows.esp`
- [x] `Real Dibella priestress.esp`
- [x] `dD - Enhanced Blood Main.esp`
- [x] `SolitudeBetterDocks-SDD-CompatiblePatch.esp`
- [x] `Summon Behemot Dragon.esp`
- [x] `AdvancedKillMoves.esp`
- [x] `AB?T - Faster (Arrows)?(Bolts)? Improved (\+\d{1,3}%)\.esp`
- [x] `GDO_Plugin_SkyRe.esp`
- [x] `MXMaxAllSkills.esp`
- [x] `zzLSARAddon.esp`
- [x] `NoMoreVanillaHair.esp`
- [x] `Dwarf Race.Esp`
- [x] `Gimli.Esp`
- [x] `Gollum.Esp`
- [x] `Halfling Race.Esp`
- [x] `Sam Merry and Peppin.Esp`
- [x] `Frodo Sam Merry & Peppin.Esp`
- [x] `RZW_ChubbyRaces.esp`
- [x] `Aragorn.Esp`
- [x] `Boromir.Esp`
- [x] `follower pack orcs.esp`
- [x] `Gandalf.Esp`
- [x] `Legolas.Esp`
- [x] `AlvhildeLycan.esp`
- [x] `Angelina Jolie.esp`
- [x] `Angelina Jolie UNP.esp`
- [x] `Braithwen Fernleaf( Archer| Auburn| Auburn Auto)?\.esp`
- [x] `Cicero.esp`
- [x] `FelixConstantine.esp`
- [x] `HousecarlWhiterun Sexy Lydia v0.5.esp`
- [x] `Maerwen Briaerthorne.esp`
- [x] `Onmeya.esp`
- [x] `Serana_Revised.esp`
- [x] `Change Follower Outfits Redux.esp`
- [x] `LiFE.esp`
- [x] `Volrath - Enhanced Lights and Fixes - RCRN.esp`
- [x] `Volrath - Enhanced Lights and Fixes - RCRN - Lanterns Of Skyrim.esp`
- [x] `GreenWaterFix_CompWithWATER1_5b.esp`

Many of these are cothing and armour mods requiring a body mod, so they could also be aliased. Some of these requirements may be masters, in which case a `req` entry is not needed.

**Comment by egocarib** [comment]
The body mods (CBBE or DIMONIZED UNP) don't appear to have any esp or other identifying file, so I don't know if we'll be able to convert them to `req` entries. They're just texture/mesh replacers. (I haven't looked over the entire list above, so there still might be some other things than can be converted.)

**Comment by WrinklyNinja** [comment]
> The body mods (CBBE or DIMONIZED UNP) don't appear to have any esp or other identifying file, so I don't know if we'll be able to convert them to req entries.

I thought at least some of the above mods would be like that. In such cases, aliasing the message should be sufficient improvement.

**Comment by Ortham** [comment]
The SkyRe plugins above remain unticked because the requirement only seems to be for a subset of functionality.
