### ISSUE TITLE
Turn incompatibility messages into proper metadata

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/skyrim#72]
Offending entries:
- [ ] `ImmersiveContentExteriorLighting.esp`
- [x] `calientevanillaarmor - banditpack curvy.esp`
- [x] `calientesvanillaarmor - banditpack slim.esp`
- [x] `cbbev3_vanillapack.esp`
- [x] `Birds.esp`
- [x] `Birdsclean.esp`
- [x] `Cumulable Blessings.esp`
- [ ] `DrinkingGivesYourBottles.esp`
- [x] `jbs_item_breakdown_rev.esp`
- [x] `Kuun''s angels drop worn armor.esp`
- [x] `MAD Ingots & Leather.esp`
- [x] `Monster Mounts Dawnguard.esp`
- [x] `Nocturnal Craftable Armors.esp`
- [x] `RecettesSansSel.esp`
- [x] `People Have Torches.esp`
- [x] `Perks Unbound - Helmless Warrior.esp`
- [x] `rt_Animal - Processing.esp`
- [x] `SwiftPotion.esp`
- [x] `Tailoring No Perks.esp`
- [x] `Valdacil''s Item Sorting - Smithing No Smelter Categories.esp`
- [x] `Where''s My Horse Gone Essential Horses.esp`
- [x] `AngisEvenBetterBow.esp`
- [x] `AngisEvenBetterBetterBow.esp`
- [x] `Cloaks.esp`
- [x] `Cloaks - No Imperial.esp`
- [x] `Cloaks - Player Only.esp`
- [x] `Cloaks - Dawnguard.esp`
- [x] `Cloaks - No Imperial - Dawnguard.esp`
- [x] `Cloaks - Player Only - Dawnguard.esp`
- [x] `1nivWICCloaks.esp`
- [x] `1nivWICCloaksCRAFT.esp`
- [x] `1nivWICCloaksNoGuards.esp`
- [x] `Crossbows_Basic_Collection_EN.esp`
- [x] `Enchanting Scrolls.esp`
- [x] `Flare Arrow Explosive.esp`
- [x] `Flare Arrow.esp`
- [x] `MorrowindGlass.esp`
- [ ] `NA_Trueflame_Unenchanted_(Eng|Rus)\.esp`
- [x] `NordLederruestung.esp`
- [x] `PocketProtectorsStarter.esp`
- [x] `RagnvaldBookFarengar+Ragnvald.esp`
- [x] `RagnvaldBookFarengar.esp`
- [x] `RoH - No Disease And Selection.esp`
- [x] `SpellbreakersLOREFRIENDLY.esp`
- [x] `Tales of Tamriel - Merchants.esp`
- [x] `WeaponsOf3E(-alpha|-beta|_Replacer)?\.esp`
- [ ] `3rdEraWeaponsMoS.esp`
- [x] `Smithing Perks Overhaul( - Balanced)?\.esp`
- [x] `Complete Crafting Overhaul( - BS version)?\.esp`
- [x] `Bouilleur de cru.esp`
- [ ] `Legendary Lore - Dragons.esp`
- [ ] `Dragon Overhaul.esp`
- [x] `Requiem - Difficulty Bar Restored.esp`
- [x] `Requiem - No Overencumbered Messages.esp`
- [x] `Requiem - TrainUnitsPerLevel10.esp`
- [x] `Requiem - TrainUnitsPerLevel100.esp`
- [x] `Requiem - TrainUnitsPerLevel5.esp`
- [x] `Requiem - Weapon Damage Modifier 3x Vanilla.esp`
- [x] `ERSO 22 - Better Necromancy Spells.esp`
- [x] `SkyRe_Main.esp`
- [x] `SkyRe_Main_NoDawnguard.esp`
- [x] `SkyRe Nordic Conqueror Armor - Realistic.esp`
- [x] `28 Days and a Bit 5.esp`
- [x] `AGameOfThronesEnglish.esp`
- [x] `DVCLight.esp`
- [x] `Houses Free and Furnished but Not Hjerim.esp`
- [x] `LevelersTowerRemod.esp`
- [x] `Mage Tower Battle Mage Edition.esp`
- [x] `mannyBlackRock.esp`
- [x] `mannyDragonhead.esm`
- [x] `N70MountainsideHomeStuds.esp`
- [x] `Sanc CastleNoLock.esp`
- [x] `secretroom-bh-en.esp`
- [x] `SolitudeBetterDocks-SoG-Compatible Version.esp`
- [x] `Terramis_Dungeon_01.esp`
- [x] `The Descent_rus.esp`
- [x] `The Secret Room of Breezehome.esp`
- [x] `tinymagetowernpainnogain.esp`
- [x] `tinytreehomebarebones.esp`
- [x] `unicorncave.esp`
- [x] `ICP Whiterun Exterior.esp`
- [x] `AethEbonyCrownReplacer.esp`
- [x] `Arvak Dark Power Voice power version.esp`
- [x] `Arvak, Shadowmere''s Body - No Saddle.esp`
- [x] `Arvak_Frost.esp`
- [x] `Arvak_Storm.esp`
- [x] `mod1.esp`
- [x] `Fullcamprespawn.esp`
- [x] `Isharas_MLLY_MALES_SKSE.esp`
- [x] `Jarls sit up straight.esp`
- [x] `No Falling Damage.esp`
- [x] `NoAutoSkillBooks(Better).esp`
- [x] `Passive Dragons (non-aggressive to all potentially friendly factions).esp`
- [x] `RangerNightingale.esp`
- [x] `Uncle Sheo does JaySuS NO TITLE.esp`
- [x] `valkiirs_tastier_food_hearthfire.esp`
- [x] `vanillaarcheryimproveddawnguard.esp`
- [x] `WerewolvesOccurringNaturally.esp`
- [x] `Riverwood Enhanced - Detailed Cities.esp`
- [x] `Riverwood Enhanced - NO NPC.esp`
- [x] `MoreForestsLODckm - Copy.esp`
- [x] `ArcaneFist - Expert to Master.esp`
- [x] `ArcaneFist - Nerf Version NS.esp`
- [x] `ArcaneFist - Nerf Version.esp`
- [x] `MidasSkyrim.esp`
- [x] `MiningFlames.esp`
- [x] `Total Voidmagic.esp`
- [x] `Excalibur _firebreath_IMBA ver.esp`
- [x] `Shout-tastic_no CD.esp`
- [x] `Clear Skies Fix - CoT version.esp`
- [x] `ForgottenMagic_Redone.esp`
- [x] `More Accessible Magicka.esp`
- [x] `BalancedCombat2.5.esp`
- [x] `CombatMoraleNoLootBag.esp`
- [x] `The Dance of Death - Dawnguard Edition.esp`
- [ ] `ACE Archery.esp`
- [x] `LB_MuchAdoSnowElves_ACE_Patch_Long.esp`
- [x] `Perk_Heavy_Armor_Tree_Redone_No_Stagger.esp`
- [x] `perk tweak.esp`
- [x] `Stealth Skills Rebalanced_LOCKPICKING.esp`
- [x] `Stealth Skills Rebalanced_PICKPOCKET.esp`
- [x] `Stealth Skills Rebalanced_SNEAK.esp`
- [x] `SmithingTreeDG.esp`
- [x] `JNPC_SeranaB.esp`
- [x] `AROP- Altmer.+\.esp`
- [x] `AROP- Argonian.+\.esp`
- [x] `AROP- Redguard.+\.esp`
- [x] `Better Racials- .+\.esp`
- [x] `NoClearedCellRespawn.esp`
- [x] `waterfxgetwet.esp`
- [x] `EnableBlackreachMap+M.esp`
- [x] `EnableForgottenValeMap+M+EA.esp`
- [x] `EnableSoulCairnMap+M.esp`
- [x] `frostmournebladeNoEnchant.esp`

A few of these entries are in pairs that only contain a message saying the other plugin is incompatible: in such cases only one of the entries needs to be kept.

Some entries are of the `Use only one` format, but provide all the relevant plugin names in a condition, so can be better implemented as a finite incompatibility list.

**Comment by Ortham** [comment]
The remaining unticked entries in the list above cannot be converted to incompatibility messages because their conditions use wildcard regex, so exact filenames cannot be determined.
