### ISSUE TITLE
Automatically converted compound conditions can be simplified

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/skyrim#73]
When the masterlist was converted from BOSS's, the converter added extra brackets in compound conditions, to compensate for the change in evaluation order.

Such compound conditions begin with `(`, and searching for `condition: '(` gives 125 matches. Most of these may have brackets that are unnecessary, so can be removed.

**Comment by egocarib** [comment]
I think I got them all in 7a43840d1cd79c8604798a1bd33a164f4aa6bc46, but I'll leave this open until I can take a second pass.
