### ISSUE TITLE
Metadata entry for USLEEP

### ISSUE THREAD

**Issue by Arthmoor** [loot/skyrim#82]
Unofficial Skyrim Legendary Edition Patch.esp needs to be added to the metadata list. It should get the same priority settings as the USKP and if needed, should be specified to load after the 3 official DLCs.

Also if possible it should generate a warning to the user if USLEEP is active at the same time any of the previous patches are active since having any of the old patches active alongside USLEEP would be bad. Very bad.

**Comment by WrinklyNinja** [comment]
It will have the 3 DLCs as masters, yes? Also, what about:

* Bash Tags - should I just copy those from the individual patches?
* The SMPC plugins - should I set them to load after USLEEP too?

**Comment by Arthmoor** [comment]
Bash tags: {{BASH:C.Climate,C.Encounter,C.ImageSpace,C.Light,C.Location,C.Music,C.Name,C.Owner,C.Water,Delev,Graphics,Invent,Names,Relev,Sound,Stats}}

As far as SMPC, the author has taken it down with a warning about it being dangerous. It won't be getting updated for USLEEP at all so I don't know how that wants to get handed in LOOT. IMO, since the author is now saying it's dangerous, maybe a message about that can go in now to notify people?

**Comment by WrinklyNinja** [comment]
OK, done.
