### ISSUE TITLE
Deactivate Tags

### ISSUE THREAD

**Issue by shadowslasher410** [loot/skyrim#94]
So, i'm in the process of going through the masterlist and tidying it up. Anyway, I figured I should probably consult the community on this one, as a ton of mods (mostly those further up in the list) have them. They're deactivate tags with a condition for another file. 

Ex: ModA.esp
     tags:
      - Deactivate
      condition: 'file("ModB.esp")'

I'm guessing this was some primitive way of telling users either: 1. ditch ModA in favor of ModB or 2. don't use ModA and ModB together.

So if that is the case, what (if anything) should be done about it? Should the tags be removed and an inc: or a useOnlyOneX added? Should we keep them? What do you guys think?

**Comment by WrinklyNinja** [comment]
No, they're Bash Tags, they influence Wrye Bash's behaviour when it builds a Bashed Patch. I can't recall what Deactivate does specifically, but it'll be documented somewhere.

**Comment by shadowslasher410** [comment]
I looked it up. According to Wrye Bash's readme, the Deactivate tag means the mod should be deactivated. I guess that means that they're okay if you're not using Wrye Bash? I didn't know that they were only for when Wrye Bash builds a bashed patch.
